# Generated by Django 5.0.7 on 2026-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_promocode_alter_baseuser_bonus_balance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalanceTransaction',
            new_name='BonusTransaction',
        ),
        migrations.AlterModelOptions(
            name='bonustransaction',
            options={'verbose_name': 'Изменение бонуса пользователя', 'verbose_name_plural': 'Изменения бонусов пользователя'},
        ),
        migrations.RenameField(
            model_name='bonustransaction',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='promocode',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='userpromocode',
            unique_together={('user', 'promo_code')},
        ),
        migrations.AddIndex(
            model_name='bonustransaction',
            index=models.Index(fields=['user', '-date_created'], name='users_bonus_user_id_3eb9ed_idx'),
        ),
    ]
