# Generated by Django 5.0.7 on 2026-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_balancetransaction_bonustransaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonustransaction',
            old_name='summ',
            new_name='amount',
        ),
    ]
