# Generated by Django 5.0.7 on 2026-05-29 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_summ_bonustransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
